---
driver:
  name: dokken
  chef_version: latest
  privileged: true # because Docker and SystemD/Upstart

transport:
  name: dokken

provisioner:
  name: dokken
 
verifier:
  name: inspec
  sudo: true

platforms:
  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install apt-transport-https lsb-release procps net-tools -y
    driver_config: 
      network:
        - ["private_network", {ip: "192.168.34.34"}]
 
  - name: centos-7
    driver:
      image: centos:7
      platform: rhel
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install lsof which systemd-sysv initscripts wget net-tools
    driver_config: 
      network:
        - ["private_network", {ip: “192.168.34.35"}]

suites:
  - name: default
    run_list:
      - recipe[hello_webpage_chef]
    attributes:
