---
driver:
  name: docker
  forward: 80
  use_sudo: false
 
provisioner:
  name: shell
 
#verifier:
#  name: inspec
#  sudo: true

platforms:
  - name: ubuntu-16.04
    driver_config:
      image: ubuntu:16.04
      platform: ubuntu
 
suites:
  - name: default
    verifier:
      name: inspec
      inspec_tests:
        - supermarket://dev-sec/cis-docker-benchmark
    attributes:
