---
driver:
  name: vagrant
  #network:
  #  - ["private_network", {ip: "192.168.34.34"}]

provisioner:
  name: chef_zero

verifier:
   name: inspec

platforms:
  - name: ubuntu-16.04
    driver_config: 
      network:
        - ["private_network", {ip: "192.168.34.34"}]
  - name: centos-7.3
    # there is some issue with this networking and I keep getting
    # /opt/vagrant/embedded/lib/ruby/2.2.0/ipaddr.rb:559:in `in6_addr': invalid address (IPAddr::InvalidAddressError)
    #driver_config: 
    #  network:
    #    - ["private_network", {ip: “192.168.34.35"}]

suites:
  - name: default
    run_list:
      - recipe[hello_webpage_chef::default]
    attributes:
