sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-current-trusty
      # - chef-stable-trusty
    packages:
      - chefdk

install: echo "skip bundle install"

branches:
  only:
    - master

services: docker

env:
  matrix:
  - INSTANCE=default-centos-7
  - INSTANCE=default-ubuntu-1604

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"

script: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

matrix:
  include:
    - before_script:
      - eval "$(/opt/chefdk/bin/chef shell-init bash)"
      - /opt/chefdk/embedded/bin/chef --version
      - /opt/chefdk/embedded/bin/cookstyle --version
      - /opt/chefdk/embedded/bin/foodcritic --version
    - script:
      - /opt/chefdk/bin/chef rake
      env: UNIT_AND_LINT=1

after_failure: cat docker_daemon.log
