name 'hello_webpage_chef'
maintainer 'Aaron Blythe'
maintainer_email 'andybly1@gmail.com'
license 'all_rights'
description 'Installs/Configures hello_webpage_chef'
long_description 'Installs/Configures hello_webpage_chef'
version '0.2.0'

depends 'apache2'
depends 'apt'
