name 'hello_webpage_chef'
maintainer 'Aaron Blythe'
maintainer_email 'andybly1@gmail.com'
license 'all_rights'
description 'Installs/Configures hello_webpage_chef'
long_description 'Installs/Configures hello_webpage_chef'
issues_url 'https://github.com/aaronblythe/hello_webpage_chef/issues'
source_url 'https://github.com/aaronblythe/hello_webpage_chef'
version '0.11.0'
supports 'ubuntu'
chef_version '>= 12.5' if respond_to?(:chef_version)

depends 'apache2'
depends 'iis'
depends 'apt'
